### ISSUE TITLE
What are the exact preprocessing steps for the fluoroscopy images?

### ISSUE THREAD

**Issue by eigenvivek** [rg2/DeepFluoroLabeling-IPCAI2020#3]
I am trying to recapitulate the preprocessing steps you mention in the README:

> The preprocessing steps consist of cropping 50 pixels from each border to remove collimator effects, log transforming the projection data, rotation to ensure patient is "up," and downsampling.

I can't get the log transform step quite right. Here's what I've tried so far:

```python
import h5py
import matplotlib.pyplot as plt
import torch
from torchvision.transforms.functional import center_crop, resize

fullres = h5py.File("ipcai_2020_full_res_data.h5", "r")
downsam = h5py.File("data/ipcai_2020_ds_8x.h5", "r")

# Full-res image
idx = 20
img = fullres[f"17-1882/projections/{idx:03d}/image/pixels"][:]

# Processing the full-res image
img_ = torch.from_numpy(img)
img_ = center_crop(img_, [1536-50, 1536-50])  # Crop 50 pixels from each border to remove collimator effects
img_ = -img_.log()  # Log-transform the projection data
img_ = resize(img_.unsqueeze(0).unsqueeze(0), [180, 180], antialias=True).squeeze()  # Downsample

# Get the preprocessed image
dsimg = downsam["01/projs"][:]

plt.figure(constrained_layout=True, dpi=300, figsize=(10, 2.5))
plt.subplot(131)
plt.imshow(img, cmap="gray")
plt.colorbar()
plt.title("Full-res image")
plt.subplot(132)
plt.imshow(img_, cmap="gray")
plt.colorbar()
plt.title("My processed image")
plt.subplot(133)
plt.imshow(dsimg[idx], cmap="gray")
plt.colorbar()
plt.title("Your preprocessed image")
plt.show()
```

which produces
![download](https://github.com/rg2/DeepFluoroLabeling-IPCAI2020/assets/29757116/c8ceddcc-3fa4-4c4a-9f2e-6246556d212f)

I'm guessing you've implemented the log transform differently?

Thank you for taking the time to organize and document this dataset so thoroughly! It's a joy to work with.

**Comment by eigenvivek** [comment]
Also the relationship between your transform and mine is not exactly linear, which is what I would expect if the difference were something small like adjusting for the linear attenuation coefficient.

![download (2)](https://github.com/rg2/DeepFluoroLabeling-IPCAI2020/assets/29757116/edd00f49-89dd-46cb-9f0a-183c8c5eb826)

**Comment by rg2** [comment]
Hi @eigenvivek , thanks a lot for the great question and kind words. You can find the C++ code that was used for performing the log remapping here: https://github.com/rg2/xreg/blob/c2bdd99b5ddd91e4561ee5d8f1572274182ba2b8/lib/image/xregImageIntensLogTrans.cpp#L54

A brief comment on what it does is here: https://github.com/rg2/xreg/blob/c2bdd99b5ddd91e4561ee5d8f1572274182ba2b8/lib/image/xregImageIntensLogTrans.h#L34

Copying that here for convenience:
Assumes the basic imaging equation: I_f(i,j) = I_0  exp(-L(i,j)), where L(i,j) is the line integral that sums linear attenuation units and is equal to \int_0^1 V(l(i,j,t)) dt.
For each pixel: L(i,j) = -log(I_f(i,j) / I_0) for I_f(i,j) != 0.
For I_f(i,j) == 0, we set L(i,j) = L(i*,j*), where i*,j* = argmin_u,v I_f(u,v), such that I_f(u,v) > 0.

For this data I_0 is approximated by the largest I_f(i,j) (e.g. assumes that there is a pixel where there was no attenuating tissue). Due to noise, the image is first smoothed and then the max is found.

Take a look at the .cpp and let me know if I can help explain in more detail.

**Comment by rg2** [comment]
I also used smoothing + a B-spline interpolator for resampling the image to smaller dimensions. That is probably different than what the torch resize function does. Looks it will do some smoothing followed by linear interpolation. That could explain some other differences.

**Comment by eigenvivek** [comment]
I was able to reproduce the downsampling, thank you for the detailed instructions!
